### ISSUE TITLE
一直在找的项目，希望能一直更新下去

### ISSUE THREAD

**Issue by bnnd** [xiaomeng79/istio-micro#1]
希望能标注下，操作系统，golang适用版本，go-micro适用版本，istio版本，docker版本，等较少掉坑。或者做成自动化部署，不用管安装部署的，专心业务。

**Comment by xiaomeng79** [comment]
好的,我加一下,如果是linux系统,安装有docker-compose,可以直接执行make allbuild && make compose,直接运行

**Comment by xiaomeng79** [comment]
已加,同时更新的增量sql如何更新
