### ISSUE TITLE
make compose up报错ERROR: Service 'srv_user' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder728770187/srv_user: no such file or directory

### ISSUE THREAD

**Issue by Magin-CC** [xiaomeng79/istio-micro#2]
```
$ make compose up
docker-compose up
Password:
Building srv_user
Step 1/7 : FROM alpine:3.2
 ---> 98f5f2d17bd1
Step 2/7 : RUN set -xe && apk add --no-cache tzdata && cp -r -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
 ---> Using cache
 ---> 51ebec833932
Step 3/7 : ADD srv_user /srv_user
ERROR: Service 'srv_user' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder728770187/srv_user: no such file or directory
make: *** [compose] Error 1
```
mac系统，装的是桌面版docker18.09.0，在本机上不存在/var/lib/docker目录，百度搜了下说是docker mac是在mac上建了个linux虚拟机，遂找到目录
``~/Library/Containers/com.docker.docker/Data/vms/0``
只是不知道要怎么样能让该项目在我这种电脑的情况下正常运行起来？

**Comment by xiaomeng79** [comment]
@Magin-CC 你好,如果你执行 `make allbuild`编译好服务,到`deployments/bin/srv_user`下查看是否编译成功,如果没有`srv_user`服务,构建镜像因为在上下文找不到文件会报错, 你可以在`deployments/docker-compose.yml`文件中第92行,更改docker.sock的路径,原路径为`    - /var/run/docker.sock:/var/run/docker.sock`,你先试一试,不行再联系
