### ISSUE TITLE
k8s集群kafka连接

### ISSUE THREAD

**Issue by IvenSky** [xiaomeng79/istio-micro#4]
你好，如何用你的kafka类连接k8s里面部署的kafaka集群，我试了很久，一直是超时

**Comment by xiaomeng79** [comment]
你好,不知道返回的超时的kafka地址是多少?应该是地址不正确,你有没有定义配置文件kafka的地址,可以在你的k8s配置文件定义环境变量  `        env:
        - name: CONFIGOR_KAFKA_ADDRS
          value: kafka:9092`
 这里的值`kafka:9092`替换为你的kafka服务名称和端口

**Comment by IvenSky** [comment]
ok，找到原因了，是我用的NodePort端口,但是在不同网段的另一台服务器连接时,连接zookeeper超时，目前还没有将微服务放进k8s进群，用的外部端口测试。多谢了
