### ISSUE TITLE
请问jaeger的 trace是不是没有启用？

### ISSUE THREAD

**Issue by mark-libn** [xiaomeng79/istio-micro#5]
我跑起这个项目来，登录jaeger的ui ，里面没有service

**Comment by xiaomeng79** [comment]
docker_compose文件中默认的跟踪地址是`CONFIGOR_TRACE_ADDRESS: jaeger:6831`,你可以设置成`http://jaeger:14268/api/traces?format=jaeger.thrift`试一下

**Comment by xiaomeng79** [comment]
我已经更新了源码,默认设置成1了,你也可以更新一下

**Comment by mark-libn** [comment]
好的非常感谢

**Comment by mark-libn** [comment]
我在阿里云k8s集群里，部署了一下，可以访问frontend和backend，但是 调用srv总是报错，如下，
{"level":"error","@timestamp":"2019-11-21T09:05:00.611+0800","caller":"backend/user.go:131","msg":"rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed","project":"api-backend","trace_id":"system","parent_id":"0","span_id":"0","stacktrace":"github.com/xiaomeng79/go-log/plugins/zaplog.(*Log).Error\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/xiaomeng79/go-log/plugins/zaplog/sugar.go:36\ngithub.com/xiaomeng79/go-log.Error\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/xiaomeng79/go-log/init.go:26\nistio-micro-mark/api/backend.UserQueryAll\n\t/Users/libn/goworkspace/src/istio-micro-mark/api/backend/user.go:131\ngithub.com/labstack/echo.(*Echo).Add.func1\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/labstack/echo/echo.go:482\nistio-micro-mark/internal/api.MetricsFunc.func1.1\n\t/Users/libn/goworkspace/src/istio-micro-mark/internal/api/middle.go:95\nistio-micro-mark/internal/api.TraceHeader.func1\n\t/Users/libn/goworkspace/src/istio-micro-mark/internal/api/middle.go:76\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/labstack/echo/middleware/cors.go:113\ngithub.com/labstack/echo/middleware.LoggerWithConfig.func2.1\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/labstack/echo/middleware/logger.go:116\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/labstack/echo/middleware/recover.go:78\ngithub.com/labstack/echo.(*Echo).ServeHTTP\n\t/Users/libn/goworkspace/src/istio-micro-mark/vendor/github.com/labstack/echo/echo.go:594\nnet/http.serverHandler.ServeHTTP\n\t/Users/libn/go/go1.13/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/Users/libn/go/go1.13/src/net/http/server.go:1890"}
{"time":"2019-11-21T09:05:00.611681447+08:00","id":"ca3e276c-fd49-4879-8027-f6ea25420b04","remote_ip":"210.12.54.18","host":"47.93.131.17","method":"GET","uri":"/backend/v1/user?","status":500, "latency":399449,"latency_human":"399.449µs","bytes_in":0,"bytes_out":50}

请问您在阿里云部署过吗？

**Comment by xiaomeng79** [comment]
1. 看看srv启动没有
2. 看看frontend和backend是否配置了正确的srv访问地址

**Comment by mark-libn** [comment]
srv启动了，可能是配置原因，也有可能是redis或者db连接错误，我再试试吧，谢谢！！！
